### ISSUE TITLE
Better Title Field

### ISSUE THREAD

**Issue by matthewwong525** [fleetingnotes/fleeting-notes-flutter#638]
**Is your feature request related to a problem? Please describe.**
Title field doesn't really fit with a lot of workflows

**Describe the solution you'd like**
- [x] cursor in the title first to quickly giving the note a title.
- [x] Title should always capitalise first letter by default (right now it doesn’t)
- [x] While in the title you should be able to press return and end up in the main text section (instead of the “done” button currently occupying the return space in the title section). This also enables users not wanting to start by adding a title to just skip that by pressing return.
- [x] We are able to add duplicate titles & titles with invalid characters (add test to ensure that search by title gets most recent note)

**Describe alternatives you've considered**
Starting in content field. But sometimes people just want to write the title first. Also, by having the return functionality, people can easily just press return and go to the content field.

**Additional context**
May want to hide source field first

**Comment by Zortecatua** [comment]
yes: cursor in the title first to quickly giving the note a title.
yes: Title should always capitalise first letter by default (right now it doesn’t)
yes: While in the title you should be able to press return and end up in the main text section (instead of the “done” button currently occupying the return space in the title section). This also enables users not wanting to start by adding a title to just skip that by pressing return.
no: We are able to add duplicate titles & titles with invalid characters (add test to ensure that search by title gets most recent note)

**Comment by matthewwong525** [comment]
@Zortecatua can you tell me more about how you use the duplicate title & invalid titles check. Maybe I can add a warning rather than a straight up restriction. I had some bug reports regarding this and I thought it'd probably be better to remove it. Considering that it isn't a restriction for apps like Google Keep or apple notes

**Comment by matthewwong525** [comment]
For now I will keep the checks but they will just be warnings.
